// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: protobuff/loan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_CreateNewLoan_FullMethodName  = "/pb.LoanService/CreateNewLoan"
	LoanService_GetOutstanding_FullMethodName = "/pb.LoanService/GetOutstanding"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	CreateNewLoan(ctx context.Context, in *CreateNewLoanRequest, opts ...grpc.CallOption) (*LoanResponse, error)
	GetOutstanding(ctx context.Context, in *GetOutstandingRequest, opts ...grpc.CallOption) (*OutstandingResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) CreateNewLoan(ctx context.Context, in *CreateNewLoanRequest, opts ...grpc.CallOption) (*LoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, LoanService_CreateNewLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetOutstanding(ctx context.Context, in *GetOutstandingRequest, opts ...grpc.CallOption) (*OutstandingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutstandingResponse)
	err := c.cc.Invoke(ctx, LoanService_GetOutstanding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
type LoanServiceServer interface {
	CreateNewLoan(context.Context, *CreateNewLoanRequest) (*LoanResponse, error)
	GetOutstanding(context.Context, *GetOutstandingRequest) (*OutstandingResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) CreateNewLoan(context.Context, *CreateNewLoanRequest) (*LoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetOutstanding(context.Context, *GetOutstandingRequest) (*OutstandingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutstanding not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_CreateNewLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateNewLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_CreateNewLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateNewLoan(ctx, req.(*CreateNewLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetOutstanding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutstandingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetOutstanding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetOutstanding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetOutstanding(ctx, req.(*GetOutstandingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewLoan",
			Handler:    _LoanService_CreateNewLoan_Handler,
		},
		{
			MethodName: "GetOutstanding",
			Handler:    _LoanService_GetOutstanding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuff/loan.proto",
}
