// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuff/loan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,2,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	TermMonths    int32                  `protobuf:"varint,3,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewLoanRequest) Reset() {
	*x = CreateNewLoanRequest{}
	mi := &file_protobuff_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewLoanRequest) ProtoMessage() {}

func (x *CreateNewLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewLoanRequest.ProtoReflect.Descriptor instead.
func (*CreateNewLoanRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_loan_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewLoanRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateNewLoanRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *CreateNewLoanRequest) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *CreateNewLoanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOutstandingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutstandingRequest) Reset() {
	*x = GetOutstandingRequest{}
	mi := &file_protobuff_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutstandingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutstandingRequest) ProtoMessage() {}

func (x *GetOutstandingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutstandingRequest.ProtoReflect.Descriptor instead.
func (*GetOutstandingRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_loan_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutstandingRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type LoanResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LoanId             string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount             float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	InterestRate       float64                `protobuf:"fixed64,4,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	TermMonths         int32                  `protobuf:"varint,5,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	TotalPayment       float64                `protobuf:"fixed64,6,opt,name=total_payment,json=totalPayment,proto3" json:"total_payment,omitempty"`
	OutstandingBalance float64                `protobuf:"fixed64,7,opt,name=outstanding_balance,json=outstandingBalance,proto3" json:"outstanding_balance,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoanResponse) Reset() {
	*x = LoanResponse{}
	mi := &file_protobuff_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanResponse) ProtoMessage() {}

func (x *LoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanResponse.ProtoReflect.Descriptor instead.
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_loan_proto_rawDescGZIP(), []int{2}
}

func (x *LoanResponse) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *LoanResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoanResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LoanResponse) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *LoanResponse) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *LoanResponse) GetTotalPayment() float64 {
	if x != nil {
		return x.TotalPayment
	}
	return 0
}

func (x *LoanResponse) GetOutstandingBalance() float64 {
	if x != nil {
		return x.OutstandingBalance
	}
	return 0
}

func (x *LoanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoanResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OutstandingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoanId             string                 `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	OutstandingBalance float64                `protobuf:"fixed64,3,opt,name=outstanding_balance,json=outstandingBalance,proto3" json:"outstanding_balance,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OutstandingResponse) Reset() {
	*x = OutstandingResponse{}
	mi := &file_protobuff_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutstandingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutstandingResponse) ProtoMessage() {}

func (x *OutstandingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutstandingResponse.ProtoReflect.Descriptor instead.
func (*OutstandingResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_loan_proto_rawDescGZIP(), []int{3}
}

func (x *OutstandingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OutstandingResponse) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *OutstandingResponse) GetOutstandingBalance() float64 {
	if x != nil {
		return x.OutstandingBalance
	}
	return 0
}

var File_protobuff_loan_proto protoreflect.FileDescriptor

const file_protobuff_loan_proto_rawDesc = "" +
	"\n" +
	"\x14protobuff/loan.proto\x12\x02pb\"\x8d\x01\n" +
	"\x14CreateNewLoanRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12#\n" +
	"\rinterest_rate\x18\x02 \x01(\x01R\finterestRate\x12\x1f\n" +
	"\vterm_months\x18\x03 \x01(\x05R\n" +
	"termMonths\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"0\n" +
	"\x15GetOutstandingRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"\xca\x02\n" +
	"\fLoanResponse\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12#\n" +
	"\rinterest_rate\x18\x04 \x01(\x01R\finterestRate\x12\x1f\n" +
	"\vterm_months\x18\x05 \x01(\x05R\n" +
	"termMonths\x12#\n" +
	"\rtotal_payment\x18\x06 \x01(\x01R\ftotalPayment\x12/\n" +
	"\x13outstanding_balance\x18\a \x01(\x01R\x12outstandingBalance\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"x\n" +
	"\x13OutstandingResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\tR\x06loanId\x12/\n" +
	"\x13outstanding_balance\x18\x03 \x01(\x01R\x12outstandingBalance2\x90\x01\n" +
	"\vLoanService\x12;\n" +
	"\rCreateNewLoan\x12\x18.pb.CreateNewLoanRequest\x1a\x10.pb.LoanResponse\x12D\n" +
	"\x0eGetOutstanding\x12\x19.pb.GetOutstandingRequest\x1a\x17.pb.OutstandingResponseB\x0eZ\fprotobuff/pbb\x06proto3"

var (
	file_protobuff_loan_proto_rawDescOnce sync.Once
	file_protobuff_loan_proto_rawDescData []byte
)

func file_protobuff_loan_proto_rawDescGZIP() []byte {
	file_protobuff_loan_proto_rawDescOnce.Do(func() {
		file_protobuff_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_loan_proto_rawDesc), len(file_protobuff_loan_proto_rawDesc)))
	})
	return file_protobuff_loan_proto_rawDescData
}

var file_protobuff_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuff_loan_proto_goTypes = []any{
	(*CreateNewLoanRequest)(nil),  // 0: pb.CreateNewLoanRequest
	(*GetOutstandingRequest)(nil), // 1: pb.GetOutstandingRequest
	(*LoanResponse)(nil),          // 2: pb.LoanResponse
	(*OutstandingResponse)(nil),   // 3: pb.OutstandingResponse
}
var file_protobuff_loan_proto_depIdxs = []int32{
	0, // 0: pb.LoanService.CreateNewLoan:input_type -> pb.CreateNewLoanRequest
	1, // 1: pb.LoanService.GetOutstanding:input_type -> pb.GetOutstandingRequest
	2, // 2: pb.LoanService.CreateNewLoan:output_type -> pb.LoanResponse
	3, // 3: pb.LoanService.GetOutstanding:output_type -> pb.OutstandingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_loan_proto_init() }
func file_protobuff_loan_proto_init() {
	if File_protobuff_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_loan_proto_rawDesc), len(file_protobuff_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_loan_proto_goTypes,
		DependencyIndexes: file_protobuff_loan_proto_depIdxs,
		MessageInfos:      file_protobuff_loan_proto_msgTypes,
	}.Build()
	File_protobuff_loan_proto = out.File
	file_protobuff_loan_proto_goTypes = nil
	file_protobuff_loan_proto_depIdxs = nil
}
