// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuff/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentRequest) Reset() {
	*x = MakePaymentRequest{}
	mi := &file_protobuff_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentRequest) ProtoMessage() {}

func (x *MakePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentRequest.ProtoReflect.Descriptor instead.
func (*MakePaymentRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_payment_proto_rawDescGZIP(), []int{0}
}

func (x *MakePaymentRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *MakePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MakePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type MakePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	LoanId        string                 `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PaymentDate   string                 `protobuf:"bytes,5,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentResponse) Reset() {
	*x = MakePaymentResponse{}
	mi := &file_protobuff_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentResponse) ProtoMessage() {}

func (x *MakePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentResponse.ProtoReflect.Descriptor instead.
func (*MakePaymentResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_payment_proto_rawDescGZIP(), []int{1}
}

func (x *MakePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *MakePaymentResponse) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *MakePaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MakePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MakePaymentResponse) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

var File_protobuff_payment_proto protoreflect.FileDescriptor

const file_protobuff_payment_proto_rawDesc = "" +
	"\n" +
	"\x17protobuff/payment.proto\x12\x02pb\"l\n" +
	"\x12MakePaymentRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\"\xa0\x01\n" +
	"\x13MakePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\tR\x06loanId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fpayment_date\x18\x05 \x01(\tR\vpaymentDate2P\n" +
	"\x0ePaymentService\x12>\n" +
	"\vMakePayment\x12\x16.pb.MakePaymentRequest\x1a\x17.pb.MakePaymentResponseB\x0eZ\fprotobuff/pbb\x06proto3"

var (
	file_protobuff_payment_proto_rawDescOnce sync.Once
	file_protobuff_payment_proto_rawDescData []byte
)

func file_protobuff_payment_proto_rawDescGZIP() []byte {
	file_protobuff_payment_proto_rawDescOnce.Do(func() {
		file_protobuff_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_payment_proto_rawDesc), len(file_protobuff_payment_proto_rawDesc)))
	})
	return file_protobuff_payment_proto_rawDescData
}

var file_protobuff_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuff_payment_proto_goTypes = []any{
	(*MakePaymentRequest)(nil),  // 0: pb.MakePaymentRequest
	(*MakePaymentResponse)(nil), // 1: pb.MakePaymentResponse
}
var file_protobuff_payment_proto_depIdxs = []int32{
	0, // 0: pb.PaymentService.MakePayment:input_type -> pb.MakePaymentRequest
	1, // 1: pb.PaymentService.MakePayment:output_type -> pb.MakePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_payment_proto_init() }
func file_protobuff_payment_proto_init() {
	if File_protobuff_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_payment_proto_rawDesc), len(file_protobuff_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_payment_proto_goTypes,
		DependencyIndexes: file_protobuff_payment_proto_depIdxs,
		MessageInfos:      file_protobuff_payment_proto_msgTypes,
	}.Build()
	File_protobuff_payment_proto = out.File
	file_protobuff_payment_proto_goTypes = nil
	file_protobuff_payment_proto_depIdxs = nil
}
