// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuff/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdentityNumber string                 `protobuf:"bytes,2,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_protobuff_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

type UpdateDeliquentStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityNumber string                 `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	IsDelinquent   bool                   `protobuf:"varint,2,opt,name=is_delinquent,json=isDelinquent,proto3" json:"is_delinquent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDeliquentStatusRequest) Reset() {
	*x = UpdateDeliquentStatusRequest{}
	mi := &file_protobuff_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliquentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliquentStatusRequest) ProtoMessage() {}

func (x *UpdateDeliquentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliquentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliquentStatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeliquentStatusRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *UpdateDeliquentStatusRequest) GetIsDelinquent() bool {
	if x != nil {
		return x.IsDelinquent
	}
	return false
}

type GetDeliquencyStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityNumber string                 `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeliquencyStatusRequest) Reset() {
	*x = GetDeliquencyStatusRequest{}
	mi := &file_protobuff_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliquencyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliquencyStatusRequest) ProtoMessage() {}

func (x *GetDeliquencyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliquencyStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliquencyStatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuff_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliquencyStatusRequest) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

type UserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IdentityNumber string                 `protobuf:"bytes,3,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	IsDelinquent   bool                   `protobuf:"varint,4,opt,name=is_delinquent,json=isDelinquent,proto3" json:"is_delinquent,omitempty"`
	IsActive       bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_protobuff_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *UserResponse) GetIsDelinquent() bool {
	if x != nil {
		return x.IsDelinquent
	}
	return false
}

func (x *UserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeliquencyStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityNumber string                 `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	IsDelinquent   bool                   `protobuf:"varint,2,opt,name=is_delinquent,json=isDelinquent,proto3" json:"is_delinquent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliquencyStatusResponse) Reset() {
	*x = DeliquencyStatusResponse{}
	mi := &file_protobuff_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliquencyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliquencyStatusResponse) ProtoMessage() {}

func (x *DeliquencyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliquencyStatusResponse.ProtoReflect.Descriptor instead.
func (*DeliquencyStatusResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeliquencyStatusResponse) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *DeliquencyStatusResponse) GetIsDelinquent() bool {
	if x != nil {
		return x.IsDelinquent
	}
	return false
}

var File_protobuff_user_proto protoreflect.FileDescriptor

const file_protobuff_user_proto_rawDesc = "" +
	"\n" +
	"\x14protobuff/user.proto\x12\x02pb\"P\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fidentity_number\x18\x02 \x01(\tR\x0eidentityNumber\"l\n" +
	"\x1cUpdateDeliquentStatusRequest\x12'\n" +
	"\x0fidentity_number\x18\x01 \x01(\tR\x0eidentityNumber\x12#\n" +
	"\ris_delinquent\x18\x02 \x01(\bR\fisDelinquent\"E\n" +
	"\x1aGetDeliquencyStatusRequest\x12'\n" +
	"\x0fidentity_number\x18\x01 \x01(\tR\x0eidentityNumber\"\xdb\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fidentity_number\x18\x03 \x01(\tR\x0eidentityNumber\x12#\n" +
	"\ris_delinquent\x18\x04 \x01(\bR\fisDelinquent\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"h\n" +
	"\x18DeliquencyStatusResponse\x12'\n" +
	"\x0fidentity_number\x18\x01 \x01(\tR\x0eidentityNumber\x12#\n" +
	"\ris_delinquent\x18\x02 \x01(\bR\fisDelinquent2\xe6\x01\n" +
	"\vUserService\x125\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x10.pb.UserResponse\x12K\n" +
	"\x15UpdateDeliquentStatus\x12 .pb.UpdateDeliquentStatusRequest\x1a\x10.pb.UserResponse\x12S\n" +
	"\x13GetDeliquencyStatus\x12\x1e.pb.GetDeliquencyStatusRequest\x1a\x1c.pb.DeliquencyStatusResponseB\x0eZ\fprotobuff/pbb\x06proto3"

var (
	file_protobuff_user_proto_rawDescOnce sync.Once
	file_protobuff_user_proto_rawDescData []byte
)

func file_protobuff_user_proto_rawDescGZIP() []byte {
	file_protobuff_user_proto_rawDescOnce.Do(func() {
		file_protobuff_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_user_proto_rawDesc), len(file_protobuff_user_proto_rawDesc)))
	})
	return file_protobuff_user_proto_rawDescData
}

var file_protobuff_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuff_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),            // 0: pb.CreateUserRequest
	(*UpdateDeliquentStatusRequest)(nil), // 1: pb.UpdateDeliquentStatusRequest
	(*GetDeliquencyStatusRequest)(nil),   // 2: pb.GetDeliquencyStatusRequest
	(*UserResponse)(nil),                 // 3: pb.UserResponse
	(*DeliquencyStatusResponse)(nil),     // 4: pb.DeliquencyStatusResponse
}
var file_protobuff_user_proto_depIdxs = []int32{
	0, // 0: pb.UserService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.UserService.UpdateDeliquentStatus:input_type -> pb.UpdateDeliquentStatusRequest
	2, // 2: pb.UserService.GetDeliquencyStatus:input_type -> pb.GetDeliquencyStatusRequest
	3, // 3: pb.UserService.CreateUser:output_type -> pb.UserResponse
	3, // 4: pb.UserService.UpdateDeliquentStatus:output_type -> pb.UserResponse
	4, // 5: pb.UserService.GetDeliquencyStatus:output_type -> pb.DeliquencyStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_user_proto_init() }
func file_protobuff_user_proto_init() {
	if File_protobuff_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_user_proto_rawDesc), len(file_protobuff_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_user_proto_goTypes,
		DependencyIndexes: file_protobuff_user_proto_depIdxs,
		MessageInfos:      file_protobuff_user_proto_msgTypes,
	}.Build()
	File_protobuff_user_proto = out.File
	file_protobuff_user_proto_goTypes = nil
	file_protobuff_user_proto_depIdxs = nil
}
