version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billing-net

  billing-engine:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/billing?sslmode=disable"
    ports:
      - "50051:50051"
    networks:
      - billing-net

volumes:
  postgres_data:

networks:
  billing-net: